// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxczveavifqkncyfoeae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54Y3p2ZWF2aWZxa25jeWZvZWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwODk2NTQsImV4cCI6MjA1MjY2NTY1NH0.fkkyb8OlMGnFE1h-XgEZYfXn_d4KJBAi9-BjsskW3tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);